[httpServer]
	port=":3000"
	readTimeout="1m"
	WriteTimeout="1m"
	
[tokenConfig]
	Secret="xxxx"
	Expiration="2s"
[logConfig]	
	Path = "/Users/haizhang/work/study/go/igo2/src/go-open/sample/log/"
	OutPut=""
